name: Publish Docker Image

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
        description: "The name of the image that should be used, excluding the repository (e.g. `cloud-portal`)"

jobs:
  build-and-push:
    permissions:
      id-token: write
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/datum-cloud/${{ inputs.image-name }}
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=ref,event=branch,suffix=-{{commit_date 'YYYYMMDD-HHmmss'}}
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=sha

      - name: Build and Push Docker Image
        id: push
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
